### ISSUE TITLE
Be more responsive-friendly?

### ISSUE THREAD

**Issue by gsklee** [facebookarchive/fixed-data-table#62]
Currently we have to pass the `width` of the table into the component on initial rendering, and the resulting table has a fixed width which does not response to window resizing etc. Is it possible to make the component more responsive without compromising the performance?

**Comment by ofersadgat** [comment]
You can do what I did: make the table resize to the containing div: https://github.com/ofersadgat/fixed-data-table-simple/

**Comment by jbraithwaite** [comment]
@ofersadgat That's a lot of boilerplate code… 

I feel like being responsive-friendly should be built in, especially since [the examples](http://facebook.github.io/fixed-data-table/example-object-data.html) adapt to the container size.

**Comment by afhammad** [comment]
+100

**Comment by ofersadgat** [comment]
To be fair, most of it isnt actually boilerplate code. You can use fitted table directly in your code without modification.

**Comment by parties** [comment]
Here's an example just using a window.resize handler, it's essentially what the example pages do.

https://gist.github.com/parties/a67c75c2ccc5ee6fe48a

**Comment by ofersadgat** [comment]
That example doesnt really work because it wont tell you if only a component resizes but the outermost doesnt. The way that the example handles this case is by manually refreshing and relying on React to not rerender if nothing changed.

**Comment by ehzhang** [comment]
Thanks for bringing this up. Making width an optional field would be a great addition to the table. Otherwise, I would recommend using a window.resize handler as mentioned by @parties to explicitly update the width of your table.

**Comment by gmaclennan** [comment]
I had this same problem and couldn't find any existing module to solve it, so I had a go at writing one: https://github.com/digidem/react-dimensions

It's aim is to get the dimensions of the containing element and pass them to fixed-data-table, and the dimensions when the window is resized.

Not that the containing element must have a height, or nothing will be rendered. The README isn't great, sorry about that.

You can use it as a higher order component or an ES7 decorator.

Let me know how it works and whether it is useful. My first go at a React component, so apologies for any silly mistakes.

**Comment by muraveill** [comment]
This would really be a great enhancement. Modern websites are responsive. I spent hours trying to make my fixed-data-table responsive in many different ways, and still it is a hundred times slower than the examples page, and I cannot figure out why I can make it work for width but not for height. It is a lot of code that could be common to all fixed-data-table users.

**Comment by gmaclennan** [comment]
Check https://github.com/digidem/smart-data-table/blob/master/src/data-table.jsx for an example about how to do this with https://github.com/digidem/react-dimensions

I really need to write better docs / example, but the short answer is that react-dimensions is a Higher-Order component that can be used like a mixin to add `this.props.containerWidth` and `this.props.containerHeight` to the component. Something like this:

```js
import { Table } from 'fixed-data-table'
import GetContainerDimensions from 'react-dimensions'

class DataTable extends React.Component {
  render () {
    return (
      <Table
        width={this.props.containerWidth}
        height={this.props.containerHeight}>
        {columnNodes}
      </Table>
    )
  }
}

export default GetContainerDimensions()(DataTable)
```

**Comment by muraveill** [comment]
I tried this, but it does not get rendered, although I did set a height for the parent component. What am I doing wrong ? My render function:

    var Dimensions = require('react-dimensions');
    ...

        var tab = Dimensions()(
            <Table
                rowHeight={ROW_HEIGHT}
                rowGetter={_this._rowGetter}
                rowsCount={SamplesStore.size()}
                width={this.props.containerWidth}
                height={this.props.containerHeight}
                headerHeight={HEADER_HEIGHT}
            >
            {cols}
            </Table>);

        return <div id="samples-table" style={{height:'500px'}}>
            {tab}
            </div>;

**Comment by muraveill** [comment]
And this says: "Illegal export declaration":

    var SamplesTable = React.createClass({
    ...
        return <div id="samples-table" style={{height:'200px'}}>
            <Table
                rowHeight={ROW_HEIGHT}
                rowGetter={_this._rowGetter}
                rowsCount={SamplesStore.size()}
                width={this.props.containerWidth}
                height={this.props.containerHeight}
                headerHeight={HEADER_HEIGHT}
            >
            {cols}
            </Table>);
            </div>;

    export default Dimensions()(SamplesTable)

There are a lot of things I don't understand in your package.

**Comment by muraveill** [comment]
I mean, it looks like I have to transform all of my code to make it fit in I have no idea how with an extended Component or something, while it should just be available as simple as a 'table-responsive' bootstrap class.

**Comment by gmaclennan** [comment]
Hi @muraveill, my apologies that the package is confusing. Your second attempt is close, but it's not working because I included some [ES6 code](https://babeljs.io/docs/learn-es2015/#modules) in the example, my apologies. Try changing this line:

```js
export default Dimensions()(SamplesTable)
```
to
```js
module.exports = Dimensions()(SamplesTable)
```

**Comment by muraveill** [comment]
I don't get why we need to export it. Couldn't `Dimensions()` just return a wrapped react component instead of an obscure function ? I already have a `module.exports = SomeOtherComponent`, and when I put them both in an object for the export, it does not seem to work.

**Comment by gmaclennan** [comment]
Hi @muraveill, `Dimensions()(SomeOtherComponent)` returns a wrapped react component. The API might have been simpler as just `Dimensions(SomeOtherComponent)` but I wanted to be able to define some options `Dimensions(options)(SomeOtherComponent)`. You should not export twice, just export the wrapped component. This might help: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by yoavniran** [comment]
Using the Dimensions workaround is just that. It shouldnt be brought up here as a solution to the obvious flaw in this Table component that only uses fixed width and sets it with inline styles no less! 

It should be possible to render the table so it spans the width of its container. 

+100 for this to be added.

**Comment by tkiethanom** [comment]
I don't really understand why these dimension settings are set here anyway. Look and feel should be handled in your own CSS files. The way it is now, the inline styles can't even be overwritten.

**Comment by langri-sha** [comment]
+1 for reasons pointed out by @muraveill. I don't want to take a performant table, only to butcher it with my own rendering requirements.

**Comment by muraveill** [comment]
Note that the react-dimensions package works fine now, this is what I am using in the end. Still, it should be a straightforward feature of fixed-data-table.

**Comment by mrchess** [comment]
+1 for `react-dimensions` as the solution. Using this as well.

**Comment by jludev1** [comment]
+1 Responsive friendly should be built in.
Using window resize handler is a poor man's approach. There will be cases that the table size need to be adjusted due to the dimension changes of neighboring elements (such as shown/hidden). In these scenarios, window resize handler won't work, and it's messy to use custom inter component communication.

**Comment by applebya** [comment]
+1

**Comment by mahmoudfelfel** [comment]
+1 for ```react-dimensions ``` but yes as everyone is saying, it should be built in.

**Comment by avesus** [comment]
+100

**Comment by shumuko** [comment]
+1

**Comment by ryanhca** [comment]
I don't see why it is so hard to implement a reactive container for your table component? I was able to accomplish this in a really trivial way. Simply add/remove event listeners using the react lifecycle methods and update a state property that is tied to your table's width. The team could build them in, yes, but for now everyone could just try using a little bit of vanilla JS to accomplish fluid tables with minimal effort.

**Comment by jdelafon** [comment]
@ryanhca 
1. Nobody said it was hard.
2. Should every developer really rewrite again his own version of the exact same functionality?
3. Would you trust every one of your employees on implementing it correctly (what is debounce again)?
4. Minimal effort !== no effort, and it accumulates with thousands of users.
There is no discussion about it, it is just what a library is made for. `react-dimensions` is one, and it works. The only question is could it be part of the core code instead of a separate dependency.

**Comment by wcjordan** [comment]
One thing I love about React is the composibility of its components and the power of higher order components.  I think this is a great case for using that since the existing FDT API already supports the necessary functionality for resizing.

@jdelafon your points regarding rewriting functionality and the effort it takes to find and learn a solution are valid.  I think a good way to address them is to create an example that demonstrates using a HOC like [react-dimensions](https://github.com/digidem/react-dimensions) and add it to our [FDT2 fork](https://github.com/schrodinger/fixed-data-table-2).  I'll attempt to do this over the next week..

I don't think there's value in integrating the solution directly into FDT / FDT2 since FDT isn't currently maintained, and FDT2 only has a few part time maintainers.  That won't address the issues around getting the HOC to work with an existing code base or handle specific edge cases, but maybe we can discuss and address those as they arise.

Do folks feel this is a good direction for the repo?

**Comment by ryanhca** [comment]
@jdelafon I just don't see why the solution needs to be a global one. I do trust all of the employees I work with. And by seeing all the complaints here about it not being in the core of the package I figured everyone was having a hard time with it. Sorry if my comment came at you in a rough way this morning. As for your comment ('it is what the library is made for)  I have to respectfully disagree. The library was made for displaying massive amounts of data in a table which they have accomplished at FB and now by the team maintaining the library. Everything else they've managed to accomplish has been sugar on top. You've asked for solutions to your problems and you've received them, why do you need someone else to code them for you?

**Comment by tkirda** [comment]
We are using fixed-data-table extensively and managing it's width using higher order components. I think it is not a problem for many other users as well. 

Lot's of people complain that is not maintained, but it already does what it was designed to do. And does it well.

**Comment by KamranAsif** [comment]
@tkirda I agree this library does an excellent job of handing large amounts of day, but there are a lot of small bugs that are clearly broken.

**Comment by wcjordan** [comment]
An example for doing responsive resizing with react-dimensions is now available here: 
http://schrodinger.github.io/fixed-data-table-2/example-responsive.html

**Comment by tkiethanom** [comment]
I think theres a bug in the ^example when you scroll down the page the whole table scrolls above the navigation.

**Comment by wcjordan** [comment]
Ah thanks for pointing that out.  That's an issue with the left navigation and example pages layout for FDT.  The example should be fine to use though.  I'll get the left nav issue fixed shortly.

**Comment by wcjordan** [comment]
Should be fixed now.  Thanks again for pointing that out!

**Comment by abelski21** [comment]
Is anyone has a typescript definition for react-dimensions? I'm trying to create one but still having some issues in the code. My table needs to be responsive when both side panels are expanded. I have toggleable panels in both sides of the table and I'm having hard time to make the table responsive. I'm using react fixed-data-table in typescript ES6.
